export const mainNavItems = [
  { label: "Home",     href: "/",               external: false, dropdown: null },
  { label: "Services", href: "/craft-catalog",  external: false, dropdown: null },
  { label: "FAQs",     href: "/general-faqs",   external: false, dropdown: null },
  { label: "Contact",  href: "/contact-us",     external: false, dropdown: null },
];

/* ── ARCHIVED: NCCER nav (remove before production) ── */
const _nccerNavItems_ARCHIVED = [
  { label: "CraftPro", href: "https://www.craft.pro/", external: true, dropdown: null },
  {
    label: "Explore",
    href: null,
    dropdown: {
      title: "NCCER for Organizations",
      titleHref: "/explore/",
      description: "NCCER is the nation's leader in providing construction industry education, assessments, credentials and accreditation.",
      links: [
        { label: "Associations",                    href: "/explore/associations/"                       },
        { label: "Contractors",                     href: "/explore/contractors/"                        },
        { label: "Corrections",                     href: "/explore/corrections/"                        },
        { label: "Government Entities",             href: "/explore/government/"                         },
        { label: "High Schools",                    href: "/explore/high-schools/"                       },
        { label: "Pipeline",                        href: "/explore/pipeline/"                           },
        { label: "Postsecondary",                   href: "/explore/postsecondary/"                      },
        { label: "NCCER COABE Strategic Partnership", href: "/explore/coabe-strategic-partnership/"      },
      ],
      quickLinks: [
        { label: "Contact Our WFD Solutions Team",  href: "/nccer-workforce-development-team/",  icon: "icon-message"                },
        { label: "Find a Center",                   href: "/find-a-center/",                     icon: "icon-buildings"              },
        { label: "General FAQs",                    href: "/general-faqs/",                      icon: "icon-search"                 },
        { label: "NCCER Network Directory",         href: "/nccer-network-directory/",           icon: "icon-globe"                  },
        { label: "Verify Credentials",              href: "https://www.nccer.org/verify-credentials/", icon: "icon-checkbox", external: true },
        { label: "Webinars",                        href: "/webinars/",                          icon: "icon-powerpoint"             },
        { label: "The Builders' Table Podcast",     href: "/newsroom/?category=616",             icon: "icon-link"                   },
      ],
    },
  },
  {
    label: "Crafts",
    href: null,
    dropdown: {
      title: "NCCER Programs & Crafts",
      titleHref: "/programs-crafts/",
      description: "Built for industry by industry, NCCER's training programs provide the construction education needed on today's job site.",
      links: [
        { label: "Annual Roadmap",               href: "/roadmap/"                                                               },
        { label: "Assessments",                  href: "/assessments/"                                                           },
        { label: "Construction Superintendent",  href: "/programs-crafts/programs/construction-superintendent-certification/"   },
        { label: "Crafts & Titles",              href: "/craft-catalog/"                                                         },
        { label: "Construction Foreman",         href: "/programs-crafts/programs/construction-foreman-certification/"          },
        { label: "NCCER's Online Courses",       href: "/programs-crafts/online-courses/"                                        },
        { label: "Programs",                     href: "/programs-crafts/programs/"                                              },
        { label: "Translated Resources",         href: "/translated-resources/"                                                  },
        { label: "Apprenticeship Assistance",    href: "/programs-crafts/apprenticeship-assistance/"                            },
        { label: "Agricultural Technology",      href: "/craft-catalog/agricultural-technology/"                                 },
      ],
      quickLinks: [
        { label: "Download Craft Catalog",  href: "https://www.nccer.org/craft-catalog/", icon: "icon-doc"                          },
        { label: "Instructor Toolbox",      href: "https://toolbox.nccer.org/",           icon: "icon-doc",  external: true         },
        { label: "Order Books & Modules",   href: "/order-books-modules/",                icon: "icon-link"                         },
        { label: "Program Registration",    href: "/programs-crafts/programs/",           icon: "icon-link"                         },
        { label: "Reciprocity Map",         href: "/reciprocity-map/",                    icon: "icon-map"                          },
        { label: "Verify Credentials",      href: "https://www.nccer.org/verify-credentials/", icon: "icon-checkbox", external: true },
      ],
    },
  },
  {
    label: "Credentials",
    href: null,
    dropdown: {
      title: "NCCER Credentials & Certifications",
      titleHref: "/credentials-certifications/",
      description: "NCCER's programs allow both emerging and experienced craft professionals to earn credentials and certifications that span all construction trades.",
      links: [
        { label: "Construction Superintendent Certification", href: "/credentials-certifications/construction-superintendent-certification/"  },
        { label: "Construction Site Safety Credentials",      href: "/credentials-certifications/construction-site-safety/"                  },
        { label: "Construction Foreman Certification",        href: "/credentials-certifications/construction-foreman-certification/"         },
        { label: "Industry-Recognized Credentials",           href: "/credentials-certifications/industry-recognized-credentials/"            },
        { label: "Crane, Rigger & Signal Person Certifications", href: "/credentials-certifications/crane-rigger-signal-person/"             },
        { label: "Accreditation Standards and Test Specifications", href: "/credentials-certifications/accreditation-standards/"             },
      ],
      quickLinks: [
        { label: "Create/Find NCCER Number", href: "/create-find-nccer-number/",                    icon: "icon-user"                          },
        { label: "Customer Support",         href: "/contact-us/",                                  icon: "icon-info"                          },
        { label: "Find a Center",            href: "/find-a-center/",                               icon: "icon-buildings"                     },
        { label: "Verify Credentials",       href: "https://www.nccer.org/verify-credentials/",     icon: "icon-verify",  external: true       },
      ],
    },
  },
  {
    label: "Career Pathways",
    href: null,
    dropdown: {
      title: "NCCER for Learners & Craft Pros",
      titleHref: "/learners-craft-pros/",
      description: "NCCER's programs were created by subject matter experts to provide the education needed to succeed on today's construction job site.",
      links: [
        { label: "High School & College Students", href: "/learners-craft-pros/high-school-college-students/" },
        { label: "Veterans",                       href: "/learners-craft-pros/veterans/"                     },
        { label: "Work-Based Learning",            href: "/learners-craft-pros/work-based-learning/"          },
        { label: "Women in Construction",          href: "/learners-craft-pros/women-in-construction/"        },
      ],
      quickLinks: [
        { label: "Create/Find NCCER Number", href: "/create-find-nccer-number/",                icon: "icon-user"                              },
        { label: "Find a Center",            href: "/find-a-center/",                           icon: "icon-buildings"                         },
        { label: "Start Your Career",        href: "https://www.byf.org/",                      icon: "icon-link",    external: true           },
        { label: "Take Module Test",         href: "https://www.pearsonvue.com/nccer/",          icon: "icon-assesment", external: true         },
        { label: "Take Skills Assessment",   href: "https://www.pearsonvue.com/nccer/",          icon: "icon-assesment", external: true         },
      ],
    },
  },
  {
    label: "Research",
    href: null,
    dropdown: {
      title: "Our Research",
      titleHref: "/research/",
      description: "Our research covers all aspects of craft labor, including aiding recruitment and retention, the impact of training on project performance and tips for workforce development.",
      links: [
        { label: "The ROI of Construction Training", href: "/research/roi-of-construction-training/" },
        { label: "Women in Construction",            href: "/research/women-in-construction/"        },
        { label: "ACTE Tools & Resources",           href: "/research/acte-tools-resources/"         },
      ],
      quickLinks: undefined,
    },
  },
  {
    label: "Our Impact",
    href: null,
    dropdown: {
      title: "Our Impact",
      titleHref: "https://www.nccer.org/nccer-philanthropy/",
      description: "NCCER changes lives by connecting individuals to opportunities and growing the construction industry workforce.",
      links: [
        { label: "Accountability & Results",              href: "/who-we-are/our-impact/"                          },
        { label: "Our Donors",                            href: "/nccer-philanthropy/our-donors/"                  },
        { label: "Build Your Future (BYF)",               href: "https://www.byf.org/",          external: true   },
        { label: "CareerStarter",                         href: "/careerstarter/"                                  },
        { label: "High School Builder Program",           href: "/explore/high-schools/high-school-builder-program-general/" },
        { label: "Hard Hat Heroes",                       href: "/nccer-philanthropy/hard-hat-heroes/"             },
        { label: "Community Construction Academies",      href: "/nccer-philanthropy/community-construction-academies/" },
        { label: "Rapid Recovery Construction Academies", href: "/nccer-philanthropy/rapid-recovery-construction-academies/" },
      ],
      quickLinks: [
        { label: "Annual Reports",   href: "/who-we-are/annual-reports/",      icon: "icon-file"                          },
        { label: "Podcasts",         href: "/newsroom/?category=616",           icon: "icon-unmute"                        },
        { label: "Newsroom",         href: "/newsroom/",                        icon: "icon-nccer"                         },
        { label: "Donate",           href: "/donate/",                          icon: "icon-heart",  external: true        },
      ],
    },
  },
  {
    label: "About Us",
    href: null,
    dropdown: {
      title: "Who We Are",
      titleHref: "/who-we-are/",
      description: "NCCER was created in 1996 and is an independent 501(c)(3) nonprofit educational foundation.",
      links: [
        { label: "Annual Reports", href: "/who-we-are/annual-reports/" },
        { label: "Get Involved", href: "/who-we-are/get-involved/" },
        { label: "Initiatives", href: "/who-we-are/initiatives/" },
        { label: "My NCCER Story", href: "/my-nccer-story/" },
        { label: "Newsroom", href: "/newsroom/" },
        { label: "Our Board", href: "/who-we-are/our-board/" },
        { label: "Our History", href: "/who-we-are/our-history/" },
        { label: "Our Impact", href: "/who-we-are/our-impact/" },
        { label: "Our Partners", href: "/our-partners/" },
        { label: "NCCER Philanthropy", href: "/nccer-philanthropy/" },
        { label: "The Builders' Table Podcast", href: "/newsroom/?category=616" },
      ],
      quickLinks: [
        { label: "Brand & Media Center", href: "/newsroom/brand-media-center/", icon: "icon-nccer" },
        { label: "Career Opportunities", href: "/who-we-are/career-opportunities/", icon: "icon-buildings" },
        { label: "Contact Us/Customer Support", href: "/contact-us/", icon: "icon-message" },
        { label: "Donate to NCCER", href: "/donate/", icon: "icon-heart", external: true },
        { label: "General FAQs", href: "/general-faqs/", icon: "icon-search" },
        { label: "Shop NCCER", href: "/shop-nccer/", icon: "icon-link" },
      ],
    },
  },
];